"""Sampling of stochastic energy loss

This module holds the energy-loss *sampler*: a callable
``(StragglingParams, key) -> (dE, log_w)`` mapping the straggling shape
parameters and a PRNG key to an energy loss [MeV] and an (importance) log-weight.
The log-weight is ``0.0`` for value/pathwise samplers and carries the
score-function gradient for the weight-based sampler; the driver
(``beamline.jax.integrate.stochastic.stochastic_solve``) accumulates it per
trajectory.

Two real samplers are provided, both built on a standard Landau draw generated by
inverse-transform sampling (ported from the ``feature/differentiable-rng``
branch's ``diff_random``). The physical ``StragglingParams`` are mapped to the
``scipy.stats.landau`` ``(loc, scale)`` parametrization by
``_straggling_to_landau``:

- ``landau_energy_loss_sampler`` -- the *sample-gradient* (SG) estimator: the draw
  is an affine map of a standard Landau variate, so it is pathwise-differentiable
  in ``(loc, scale)``. Its log-weight is ``0.0``.
- ``landau_energy_loss_sampler_wg`` -- the *weight-gradient* (WG) estimator: the
  draw is taken from a ``stop_gradient``-ed reference distribution and the returned
  log-weight's gradient is the score function ``d log p`` (REINFORCE-style). Its
  *value* is identical to the SG draw (the log-weight is ``0`` at the sampling
  parameters); only the gradient differs. This is the differentiable route when a
  pathwise gradient is unavailable; for the Landau the score is heavy-tailed, so
  it trades the SG tail variance for score variance rather than strictly reducing
  it.

``dummy_energy_loss_sampler`` is a crude one-sided stand-in (sum of two
exponentials with the Bethe-Bloch mean) kept for exercising the scaffolding.

Note: the samplers do **not** clamp ``dE``. Clamping the value while keeping the
WG weight would break the importance-weight identity; the rare Landau lower-tail
(negative ``dE``) and large upper-tail draws are instead absorbed downstream by
``apply_energy_loss``, which floors the total energy at the rest mass.
"""

import jax
import jax.numpy as jnp
import jax.random as jr
from jax import Array

from beamline.jax.absorber.material import StragglingParams
from beamline.jax.types import SFloat

_LANDAU_MPV_OFFSET = 0.20005183774398613
"""Offset relating the reduced-Landau most-probable value to ``scipy.stats.landau``."""


def _standard_landau(key: Array) -> tuple[SFloat, SFloat]:
    """Draw a standard Landau variate by inverse-transform sampling

    Returns the variate together with the ``aux`` intermediate (the
    location-independent part of the transform), which the reweighting formula in
    ``_landau_log_weight_ratio`` needs.
    """
    unif_key, exp_key = jr.split(key)
    pi_by_2 = jnp.pi / 2

    unif_rv = jr.uniform(unif_key, minval=-pi_by_2, maxval=pi_by_2)
    exp_rv = jr.exponential(exp_key)

    aux = (1 / pi_by_2) * (
        (pi_by_2 + unif_rv) * jnp.tan(unif_rv)
        - jnp.log((pi_by_2 * jnp.cos(unif_rv)) / (pi_by_2 + unif_rv))
    )
    std_landau = aux - jnp.log(exp_rv) / pi_by_2
    return std_landau, aux


def _landau_log_weight_ratio(
    landau_rv: SFloat,
    aux: SFloat,
    orig_loc: SFloat,
    orig_scale: SFloat,
    new_loc: SFloat,
    new_scale: SFloat,
) -> SFloat:
    """Log importance-weight ratio ``log p(landau_rv; new) / p(landau_rv; orig)``

    For a Landau variate drawn under ``(orig_loc, orig_scale)`` (with its ``aux``),
    this is the log density ratio to the ``(new_loc, new_scale)`` parametrization,
    used for importance reweighting. Ported from ``diff_random``'s
    ``_LandauBase.reweight``.
    """
    pi_by_2 = jnp.pi / 2
    orig_std = (landau_rv - orig_loc) / orig_scale
    new_std = (landau_rv - new_loc) / new_scale
    orig_exp_rv = jnp.exp((aux - orig_std) * pi_by_2)
    new_exp_rv = jnp.exp((aux - new_std) * pi_by_2)
    return (
        (orig_std - new_std) * pi_by_2
        + (orig_exp_rv - new_exp_rv)
        + (jnp.log(orig_scale) - jnp.log(new_scale))
    )


def _straggling_to_landau(params: StragglingParams) -> tuple[SFloat, SFloat]:
    """Map straggling parameters to the ``scipy.stats.landau`` ``(loc, scale)``

    ``scale = xi * pi/2`` and ``loc`` is placed so the sampled distribution's most
    probable value coincides with ``mode_energy_loss``. This matches the
    ``landau_energy_loss`` reference PDF (and the branch's ``Landau_SG``, which is
    validated against ``scipy.stats.landau``).
    """
    pi_by_2 = jnp.pi / 2
    xi = params.xi
    scale = xi * pi_by_2
    loc = (
        params.mode_energy_loss
        + xi * (1 - jnp.euler_gamma - _LANDAU_MPV_OFFSET)
        + xi * jnp.log(pi_by_2)
    )
    return loc, scale


def landau_energy_loss_sampler(
    params: StragglingParams, key: Array
) -> tuple[SFloat, SFloat]:
    """Sample an energy loss [MeV] -- value/pathwise (SG) estimator

    Draws ``dE = std_landau * scale + loc`` from a standard Landau variate, so the
    draw is pathwise-differentiable in the distribution parameters. The log-weight
    is ``0.0``.

    Args:
        params: Straggling shape parameters (uses ``xi`` and ``mode_energy_loss``).
        key: A JAX PRNG key.

    Returns:
        ``(dE, log_w)`` with ``log_w == 0.0``.
    """
    std_landau, _aux = _standard_landau(key)
    loc, scale = _straggling_to_landau(params)
    dE = std_landau * scale + loc
    return dE, jnp.zeros_like(dE)


def landau_energy_loss_sampler_wg(
    params: StragglingParams, key: Array
) -> tuple[SFloat, SFloat]:
    """Sample an energy loss [MeV] -- weight/score-function (WG) estimator

    Draws from a ``stop_gradient``-ed reference distribution and returns a
    log-weight whose gradient is the score function ``d log p``. The sample value
    carries no gradient; the gradient of the distribution parameters flows through
    the weight instead. The returned ``dE`` (and ``log_w``, which is ``0`` here)
    are numerically identical to ``landau_energy_loss_sampler``; the two differ
    only under differentiation. Use this when a pathwise gradient is unavailable;
    note the Landau score is heavy-tailed, so the gradient can be high-variance.

    Args:
        params: Straggling shape parameters (uses ``xi`` and ``mode_energy_loss``).
        key: A JAX PRNG key.

    Returns:
        ``(dE, log_w)``.
    """
    std_landau, aux = _standard_landau(key)
    loc, scale = _straggling_to_landau(params)
    loc_ng = jax.lax.stop_gradient(loc)
    scale_ng = jax.lax.stop_gradient(scale)
    dE = std_landau * scale_ng + loc_ng
    # Reweight from the (stop-grad) reference back to the traced (loc, scale); the
    # minus sign yields log p(traced) / p(reference), whose gradient is the score.
    log_w = -_landau_log_weight_ratio(
        dE, aux, orig_loc=loc, orig_scale=scale, new_loc=loc_ng, new_scale=scale_ng
    )
    return dE, log_w


def dummy_energy_loss_sampler(
    params: StragglingParams, key: Array
) -> tuple[SFloat, SFloat]:
    """Sample a (dummy) energy loss [MeV] for the given straggling parameters

    Placeholder distribution: the sum of two i.i.d. exponentials each with mean
    ``mean_energy_loss / 2``, so the total has mean ``mean_energy_loss``. The
    draw is one-sided (always positive) and differentiable in
    ``mean_energy_loss``. It does **not** reproduce the Landau/Vavilov shape; it
    is only a stand-in until the real sampler is wired in.

    Args:
        params: Straggling shape parameters (only ``mean_energy_loss`` is used).
        key: A JAX PRNG key.

    Returns:
        ``(dE, log_w)`` with ``log_w == 0.0``.
    """
    k1, k2 = jr.split(key)
    mean_each = params.mean_energy_loss / 2
    # clamp the uniforms away from 0 so log is finite (jax_debug_nans is on)
    tiny = jnp.finfo(jnp.result_type(float)).tiny
    u1 = jr.uniform(k1, minval=tiny, maxval=1.0)
    u2 = jr.uniform(k2, minval=tiny, maxval=1.0)
    dE = -mean_each * (jnp.log(u1) + jnp.log(u2))
    return dE, jnp.zeros_like(dE)
